name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my first git hib action job"
        
        - name: checkout code
          uses: actions/checkout@v4

        - name: read and list of files
          run: |
            ls -lrt
            cat README.md  

        # - name: list of files
        #   run: ls
          
        # - name: read file
        #   run: cat README.md 

              