name: matrix workflow

on:
   workflow_dispatch:
   push:
     branches: [ main ] 

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-20.04,windows-latest]
        images: [hello-world,alpine:latest]
        exclude:
         - images: alpine:latest
           os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo message
      run: docker info

    - name: run image on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}